### ISSUE TITLE
敬请增加大小写不敏感功能（Please add a case insensitive feature）

### ISSUE THREAD

**Issue by nanjingman** [xvyv99/obsidian-words-annotate#2]
如现在增加了Affordance，但查不到affordance。词和短语都请增加可选择大小写不敏感。谢谢您开发了这个如此有用的插件。赞！
（For example, Affordance has been added now, but no affordance can be found. Please add optional case insensitive words and phrases. Thank you for developing such a useful plugin. like！）

**Comment by xvyv99** [comment]
Ok, I'll add this feature as soon as I can within a week.

**Comment by nanjingman** [comment]
敬请再添加高亮已标注词，及导出单词列表: 单词，意义1，意义2，……意义n（一个单词一行，按所示分列）。谢谢！

**Comment by nanjingman** [comment]
Maybe you can refer this: https://github.com/dominiclet/obsidian-note-definitions. Thanks！

**Comment by xvyv99** [comment]
Ok, I'll add this feature as soon as I can within a week.
